### PR TITLE
desc-tex migration

### PR DESCRIPTION
**Pull request by aimalz**
I think this now works but someone else should check as well.  There are still some issues, but they can be solved after the basic framework gets into the master branch.  

(A subset of known issues is as follows: tables not being inserted from their own directory, authors.csv still being broken so everyone's commented out, numerous broken links from bibliography.  But I think this is still ready for a merge as long as someone else can run it.)

### CODE REVIEW

**Comment by sschmidt23** [comment]
I fixed the rendering of authors.csv, it now runs, thanks to some missed \&'s.  I also fixed a runaway italic in results.tex.

I'll take a detailed look at this tonight or early tomorrow.  I did a quick run of "make mnras", and one obvious problem is a couple figures aren't rendering properly:
Fig 1: bottom figures are too large and run off the right side of the page

Fig A1 in appendix: the figures are too large, and the caption runs off the bottom of the page.

**Comment by aimalz** [comment]
I had to take out your `subfigure`/`subcaption` calls because they were breaking a bunch of things.  I've never used those before and think we can get away without them by choosing appropriate sizes for the figures/captions.  I didn't do that myself, though, and only checked for successful compilation.

**Comment by sschmidt23** [comment]
Figure A1 was still too large and pushed the caption off the bottom the page, I shrank the panels a bit and now things look good in general, so I'll approve this PR.

**Review by sschmidt23 — APPROVED** [review]
Now looks good, ready to merge.

**Pull request merged**
