### PR TITLE
Merging in the branch corresponding to the first iteration of paper review

### PR DESCRIPTION
**Pull request by aimalz**
I think now is an appropriate time to sync up with Overleaf and move editing to GitHub so we can have multiple branches going at the same time.  This branch now contains the paper version that's on Overleaf.  We can start new branches for editing once it's in the `desc-tex` format and the sections are in different files.

### CODE REVIEW

**Comment by sschmidt23** [comment]
I agree, this does seem like a good time to move over.

**Comment by aimalz** [comment]
@sschmidt23 Did you mean to review this PR and merge it before closing it, or is there something wrong that I should fix?  Thanks.

**Comment by sschmidt23** [comment]
Yes, I meant to merge after closing, but was sidetracked by someone stopping by my office, sorry about that.

**Review by sschmidt23 — APPROVED** [review]
Looks good, please merge the changes.

**Pull request merged**
